#!/usr/bin/env python3

import sys
import subprocess
from youtube_search import YoutubeSearch

def usage():

  print(
  '''
  immudex-ytplay - script which could play a video or audio track from youtube
  @ 2023 (original bash script), 2025 (python script) morketsmerke.org
  Options:
    --search - search given keyword on youtube.
    --video - play youtube video.
    --audio - play only youtube video audiotrack
  Ommiting -s option, assume you are give a yt video link.
  You have to put -v or -a before you paste a yt video link
  When you put keywords in -s option, you need to choose
  that you want listening an audiotrack (--audio) oraz watch video (--video)
  Usage:
    $ immudex-ytplay --search='lofi' --audio
    $ immudex-ytplay --video https://youtube.com/watch?v=...
    $ immudex-ytplay --audio https://youtube.com/watch?v=...
  You can search again the same keywords puting 'r' or 'R' instead
  of video numer. After you choose you video or put video link script prints
  all available formats, and ask you to choose one pair of ID's - video+audio
  in this format. 
  ''')

def ytSearch(keywords, maxResults=15):
  
  i = "r"
  while isinstance(i, str) and (i == "r" or i == "R"):
    subprocess.run('clear')
    results = YoutubeSearch(keywords, max_results=maxResults).to_dict()

    index = 1
    for video in results:
      print(f"\033[1m\033[91m{index}\033[0m. Title: \033[92m{video['title']}\033[0m")
      print(f"  Channel: \033[93m{video['channel']}\033[0m, Duration: \033[94m{video['duration']}\033[0m, PubDate: \033[95m{video['publish_time']}\033[0m")
      index += 1
  
    i = input("Put number of video you wanna watch or put 'r' to reload search result: ")

  i = int(i) - 1
  return(results[i]['id'], results[i]['title'], results[i]['channel'], results[i]['duration'], results[i]['publish_time'])

def getFormat(videoID):
  subprocess.run(['yt-dlp', '--list-formats', 'https://youtube.com/watch?v=' + videoID])
  f = input("Please choose youtube video format, you need put video+audio ID of quality in this format:") 
  return f 

if len(sys.argv) < 2:
  usage()
  sys.exit(2)
  
option=sys.argv[1].split("=", 1)[0]

if option == '--search':
  if len(sys.argv) > 2:
    if sys.argv[2] == '--video':
      mode = "video"
    elif sys.argv[2] == '--audio':
      mode = "audio"
    else:
      usage()
      sys.exit(2)
    keywords = sys.argv[1].split("=", 1)[1]
    
    video = ytSearch(keywords)
    subprocess.run('clear')

    if mode == 'audio':
      ytFormat = "--no-video"
    else:
      ytFormat = "--ytdl-format=" + getFormat(video[0])

    subprocess.run('clear') 
    print(f"\033[91m1\033[0m. Title: \033[92m{video[1]}\033[0m")
    print(f"  Channel: \033[93m{video[2]}\033[0m, Duration: \033[94m{video[3]}\033[0m, PubDate: \033[95m{video[4]}\033[0m")
    print("===================================================================")
    
    subprocess.run(['mpv', ytFormat, 'https://youtube.com/watch?v=' + video[0]])
  else:
    usage()
    sys.exit(2)

elif sys.argv[1] == '--audio':
  if len(sys.argv) > 2:
    link=sys.argv[2]
    ytFormat="--no-video"
    subprocess.run(['mpv', ytFormat, link])
  else:
    usage()
    sys.exit(2)

elif sys.argv[1] == '--video':
  if len(sys.argv) > 2:
    link=sys.argv[2]
    videoID=link[-11:]
    ytFormat="--ytdl-format=" + getFormat(videoID)
    subprocess.run(['mpv', ytFormat, link])
  else:
    usage()
    sys.exit(2)   
