#!/bin/bash

function help() {
  echo "immudex-meteo - weather from wttr.in"
  echo "@ 2026 morketsmerke.org";
  echo "Opcje:";
  echo "  --short - short human readable format with one small ascii art";
  echo "  --long  - long format, more readable, weather for every stage";
  echo "            of the day and 2-day predictables";
  echo "  --micro - micro format, one line with details (actual weather)";
  echo "Usage:";
  echo "$ immudex-meteo <-slm> <miasto>";
}

if [ "$1" ]; then
  if [ "$1" = "--short" ]; then
    curl wttr.in/${2}?format=4\&lang=pl;
  elif [ "$1" = "--long" ]; then
    curl wttr.in/${2}?lang=pl;
  elif [ "$1" = "--micro" ]; then
    curl wttr.in/${2}?format=4
  fi
else
  help;
  exit 1;
fi
