#!/bin/bash

GREEN="\e[32m";
YELLOW="\e[33m";
ENDCOLOR="\e[0m";

function help() {
  echo "immudex-create-media it's script used for write iso image to usb drive.";
  echo "Script writes .iso file to usb stick - make it then bootable. This"
  echo "script prepare usb disks for 32-bit EFI systems."
  echo "Superuser (root) privileges are required.";
  echo;
  echo "Usage: immudex-create-media [--help] [--version] [--i386-efi --disk=usb_disk --isofile=immudex.iso] [--nuke --disk=usb_disk] --disk=usb_disk --isofile=file.iso";
  echo;
  echo "Options:";
  echo "  --disk=/dev/sdX                           Indicates disk device.";
  echo "  --isofile=file.iso                        Indicates iso file.";
  echo "  --i386-efi --disk=/dev/sdX immudex.iso    Creating 32-bit EFI bootable usb drive with iso image. (Compatibile with immudex images only.)";
  echo "  --nuke --disk=/dev/sdX                    Write 0's to 1st megabyte of disk, wiping partition table.";
  echo "  --help                                    Print this message.";
  echo "  --version                                 Print information about version, author and copyrights."; 
  echo;
  echo "Exmaples:";
  echo "  immudex-create-media                                                    Print this message.";
  echo "  immudex-create-media --disk=/dev/sdX --isofile=file.iso                 Writes iso file to usb stick, made it bootable."; 
  echo "  immudex-create-media --i386-efi --disk=/dev/sdX --isofile=immudex.iso   Create 32-bit EFI bootable usb stick with immudex.";
  echo "  immudex-create-media --nuke --disk=/dev/sdX                             Writes first MB with 0's, deleting partition table";
  echo;
  echo "Report bugs to <xf0r3m@gmail.com>"; 
}

function version() {
  echo "immudex-create-media 1.0";
  echo;
  echo "Copyright (C) 2026 morketsmerke.org";
  echo "This is free software; see the source for copying conditions.  There is NO";
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
  echo;
  echo "Written by xf0r3m.";
}

if [ $UID -ne 0 ]; then
  echo "Permission denied!";
  help;
  exit 1;
fi

if [ "$1" ] && [ "$1" = "--help" ]; then help; exit 0; fi
if [ "$1" ] && [ "$1" = "--version" ]; then version; exit 0; fi

if [ "$1" ] && [ "$1" = "--i386-efi" ]; then target="i386-efi"; shift; fi
if [ "$1" ] && [ "$1" = "--nuke" ]; then target="nuke"; shift; fi
if [ "$1" ] && [ "$(echo $1 | cut -d "=" -f 1)" = "--disk" ]; then
  disk=$(echo $1 | cut -d "=" -f 2); shift;
else
  help;
  exit 1;
fi
if [ ! "$target" ] || [ "$target" != "nuke" ]; then
  if [ "$1" ] && [ "$(echo $1 | cut -d "=" -f 1)" = "--isofile" ]; then 
    iso=$(echo $1 | cut -d "=" -f 2);
  else
    help;
    exit 1;
  fi
fi

if [ "$target" = "i386-efi" ]; then
  echo -n "Writing zeros to 1st megabyte on disk..."; 
  dd if=/dev/zero bs=1M of=$disk count=1 > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Creating MS-DOS partitionig scheme on disk..."; 
  parted $disk mklabel msdos > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi
  
  echo -n "Creating FAT-32 partition...";
  parted $disk mkpart primary fat32 1 100%Free > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Creating VFAT filesystem on partition...";
  mkfs.vfat ${disk}1 > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Creating /mnt/usb directory...";
  mkdir /mnt/usb > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]";
  else echo -e "[${YELLOW}Directory exist!${ENDCOLOR}]"; fi
  
  echo -n "Mounting VFAT partition on /mnt/usb...";
  mount ${disk}1 /mnt/usb > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Instalation GRUB on disk...";
  grub-install --target=i386-efi --efi-directory=/mnt/usb --boot-directory=/mnt/usb/boot --bootloader-id=boot --removable > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Creating /mnt/iso directory...";
  mkdir /mnt/iso > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]";
  else echo -e "[${YELLOW}Directory exist!${ENDCOLOR}]"; fi

  echo -n "Mounting iso file on /mnt/iso...";
  mount $iso /mnt/iso > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Copying grub config files to the disk...";
  cp /mnt/iso/boot/grub/font.pf2 /mnt/usb/boot/grub > /dev/null 2>&1;
  cp /mnt/iso/boot/grub/grub.cfg /mnt/usb/boot/grub > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Copying immudex files to the disk..."; 
  cp -r /mnt/iso/live /mnt/usb > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi
  
  echo -n "Creating empty DEBIAN file...";
  touch /mnt/usb/DEBIAN > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi
  
  echo -n "Umounting all mounted filesystems...";
  umount /mnt/usb /mnt/iso > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

elif [ "$target" = "nuke" ]; then
  echo -n "Writing zeros to 1st megabyte on disk..."; 
  dd if=/dev/zero bs=1M of=$disk count=1 > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

else
  echo -n "Writing zeros to 1st megabyte on disk..."; 
  dd if=/dev/zero bs=1M of=$disk count=1 > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi

  echo -n "Writing iso image to the disk..."
  dd if=$iso bs=1M of=$disk > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[${GREEN}OK${ENDCOLOR}]"; fi
fi 
