#!/bin/bash

GREEN="\e[32m";
RED="\e[31m";
ENDCOLOR="\e[0m";
BOLD="\e[1m";
BOLD_GREEN="\e[1;32m";
BOLD_YELLOW="\e[1;33m";
BOLD_BLUE="\e[1;34m";

function help() {
  echo "immudex-shoutcasts - A script that finds a internet radiostations based on a keyword.";
  echo "@ 2022, 2026 morketsmerke.org";
  echo;
  echo "Options:";
  echo "  --source - values: icecast or radio. This parameter can be optional in";
  echo "           this case keyword will be searched in icecast directory and";
  echo "           internet radios browser.";
  echo "  --keywords - this parameter is required. This is the keywords on which";
  echo "           the radio station searched will be based. Forbiden keywords:";
  echo "           'icecast', 'radio'. Those are reserved for source define.";
  echo;
  echo "Usage:";
  echo "$ immudex-shoutcasts [icecast/radio] keyword1 keyword2 ... keywordN";
  echo;
  echo "This script use dir.xiph.org as icecast directory and page";
  echo "radio-browser.info for searching internet radios";
}


function getDataBetweenHtmlMarks() {
  grep "$1" $2 | sed -n "${3}p" | cut -d ">" -f 2 | cut -d "<" -f 1;
}

function listOfStations() {
  query=$1;
  src=$2;
  
  case $src in
    "icecast") wget http://dir.xiph.org/search?q=$query -O /tmp/icecast.idx >> /dev/null 2>&1;
                file="/tmp/icecast.idx";;
    "radio") wget "https://de1.api.radio-browser.info/m3u/stations/search?limit=30&name=${query}&hidebroken=true&order=clickcount&reverse=true" -O /tmp/radio.idx >> /dev/null 2>&1;
              file="/tmp/radio.idx";
              dos2unix $file;
  esac
    
  if [ ! -f $file ]; then
    echo -e "${RED}There is no internet connection or sources are currently";
    echo -e "unavailable.${ENDCOLOR}";
    exit 1;
  fi

  case $src in
    "icecast") amountOfStations=$(grep 'card-title' $file | wc -l);;
    "radio") amountOfStations=$(grep '#EXTINF' $file | wc -l);;
  esac

  case $src in
    "icecast") echo -e "${BOLD}Icecast directory:${ENDCOLOR}";;
    "radio") echo -e "${BOLD}radio-browser.info:${ENDCOLOR}";;
  esac

  i=1;
  while [ $i -le $amountOfStations ]; do
    case $src in
      "icecast") stationName=$(getDataBetweenHtmlMarks 'card-title' $file $i);;
      "radio") stationName=$(grep '#EXTINF' $file | sed -n "${i}p" | cut -d "," -f 2-);;
    esac
    if [ "$src" = "icecast" ]; then
      whatIsPlayingNow=$(getDataBetweenHtmlMarks 'card-subtitle' $file $i);
    fi
    case $src in
      "icecast") link=$(grep 'Play' $file | sed -n "${i}p" | cut -d '"' -f 2);;
      "radio") link=$(grep '://' $file | sed -n "${i}p");;
    esac
    echo -e "${BOLD}${i}.${ENDCOLOR} ${BOLD_YELLOW}${stationName}${ENDCOLOR}";
    if [ "$whatIsPlayingNow" ]; then
      echo -e "\t${BOLD}Now playing:${ENDCOLOR} ${BOLD_BLUE}${whatIsPlayingNow}${ENDCOLOR}";
      unset whatIsPlayingNow;
    fi
    echo -e "\t${BOLD}Link:${ENDCOLOR} ${BOLD_GREEN}${link}${ENDCOLOR}";
    i=$(expr $i + 1);
  done
  unset i;
  echo;
}

if [ "$1" ]; then
  option=$(echo $1 | cut -d '=' -f 1);
  if [ "$option" = "--source" ]; then
    src=$(echo $1 | cut -d '=' -f 2);
    search=$(echo $* | cut -d '=' -f 3-);
  elif [ "$option" = "--keywords" ]; then
    search=$(echo $* | cut -d "=" -f 2-);
  fi
else
  help;
  exit 1;
fi

if [ "$src" ]; then
  listOfStations "$search" $src;
  if [ "$src" = "icecast" ]; then
    file="/tmp/icecast.idx";
  else
    file="/tmp/radio.idx";
  fi
else
  listOfStations "$search" 'icecast';
  listOfStations "$search" 'radio';

  PS3="source? ";
  select src in 'icecast' 'radio'; do
    case $src in
      'icecast') file="/tmp/icecast.idx";;
      'radio') file="/tmp/radio.idx";;
      *) exit 0;
    esac
    break
  done
fi

echo -n "Station? ";
read station;
if $(echo $station | grep -q '[0-9]') && [ $station -le 30 ]; then
  case $file in
    '/tmp/icecast.idx') link=$(grep 'Play' $file | sed -n "${station}p" | cut -d '"' -f 2);;
    '/tmp/radio.idx') link=$(grep '://' $file | sed -n "${station}p");;
  esac
  case $src in
      "icecast") stationName=$(getDataBetweenHtmlMarks 'card-title' $file $station);;
      "radio") stationName=$(grep '#EXTINF' $file | sed -n "${station}p" | cut -d "," -f 2-);;
  esac
  echo -e "${BOLD}Station:${ENDCOLOR} ${BOLD_YELLOW}${stationName}${ENDCOLOR}";
  mpv --no-video $link;
else
  exit 0;
fi
