#!/usr/bin/env python3

import sys
import subprocess
from youtube_search import YoutubeSearch

def usage():

  print('''immudex-ytplay script for playing a video or audio track from YouTube. Script
can search based on given keywords and return list of results. User choose
one of result or repeats searching with 'r' || 'R' answer to number from
list result. Then script quering YouTube for available formats and table
with possible format are printed. User have to put video and audio quality
from table in requested format: videoQualityID+audioQualityID. There are
a hint. Script is half-interactive.
  
Usage: immudex-ytplay [--search='keyword1...keywordN' --video | --audio] [--video youtube_link] [--audio youtube_link] [--help] [--version]

Options:
  --search='keyword1...keywordN' --video/--audio       Search given keywords on YouTube and play video or audiotrack.
  --video YouTube_Link                                 Play YouTube video.
  --audio YouTube_Link                                 Play only YouTube video audiotrack.
  --help                                               Print this message.
  --version                                            Print information about version, author and copyrights.

Examples:
  immudex-ytplay --search='lofi' --audio                  Script will be search a lofi keyword in YouTube and play only audio tracks from choosen video.
  immudex-ytplay --video https://youtube.com/watch?v=...  Script will be play a video from given link, of course is publicly available.
  immudex-ytplay --audio https://youtube.com/watch?v=...  Script will be play a audio track from given video link. The principle of video playback also applies here.

Report bugs to <xf0r3m@gmail.com>''')

def version():
  print('''immudex-ytplay 1.0

Copyright (C) 2026 morketsmerke.org
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Written by xf0r3m.''') 

def ytSearch(keywords, maxResults=15):
  
  i = "r"
  while isinstance(i, str) and (i == "r" or i == "R"):
    subprocess.run('clear')
    results = YoutubeSearch(keywords, max_results=maxResults).to_dict()

    index = 1
    for video in results:
      print(f"\033[1m\033[91m{index}\033[0m. Title: \033[92m{video['title']}\033[0m")
      print(f"  Channel: \033[93m{video['channel']}\033[0m, Duration: \033[94m{video['duration']}\033[0m, PubDate: \033[95m{video['publish_time']}\033[0m")
      index += 1
  
    i = input("Put number of video you wanna watch or put 'r' to reload search result: ")

  i = int(i) - 1
  return(results[i]['id'], results[i]['title'], results[i]['channel'], results[i]['duration'], results[i]['publish_time'])

def getFormat(videoID):
  subprocess.run(['yt-dlp', '--list-formats', 'https://youtube.com/watch?v=' + videoID])
  f = input("Please choose youtube video format, you need put video+audio ID of quality in this format:") 
  return f 

if len(sys.argv) == 2:
  if sys.argv[1] == '--help':
    usage()
    sys.exit(0)
  elif sys.argv[1] == '--version':
    version()
    sys.exit(0)

if len(sys.argv) < 2:
  usage()
  sys.exit(2)
  
option=sys.argv[1].split("=", 1)[0]

if option == '--search':
  if len(sys.argv) > 2:
    if sys.argv[2] == '--video':
      mode = "video"
    elif sys.argv[2] == '--audio':
      mode = "audio"
    else:
      usage()
      sys.exit(2)
    keywords = sys.argv[1].split("=", 1)[1]
    
    video = ytSearch(keywords)
    subprocess.run('clear')

    if mode == 'audio':
      ytFormat = "--no-video"
    else:
      ytFormat = "--ytdl-format=" + getFormat(video[0])

    subprocess.run('clear') 
    print(f"\033[91m1\033[0m. Title: \033[92m{video[1]}\033[0m")
    print(f"  Channel: \033[93m{video[2]}\033[0m, Duration: \033[94m{video[3]}\033[0m, PubDate: \033[95m{video[4]}\033[0m")
    print("===================================================================")
    
    subprocess.run(['mpv', ytFormat, 'https://youtube.com/watch?v=' + video[0]])
  else:
    usage()
    sys.exit(2)

elif sys.argv[1] == '--audio':
  if len(sys.argv) > 2:
    link=sys.argv[2]
    ytFormat="--no-video"
    subprocess.run(['mpv', ytFormat, link])
  else:
    usage()
    sys.exit(2)

elif sys.argv[1] == '--video':
  if len(sys.argv) > 2:
    link=sys.argv[2]
    videoID=link[-11:]
    ytFormat="--ytdl-format=" + getFormat(videoID)
    subprocess.run(['mpv', ytFormat, link])
  else:
    usage()
    sys.exit(2)   
