#!/bin/bash

function help() {

  echo "immudex-crypt is script used for listing, open, close and create crypt_LUKS partitions.";
  echo "Script creates 'immudex-crypt' mount points, every mount point end up with 'index'.";
  echo "Index is order number of opening crypt_LUKS devices via 'immudex-crypt' The first";
  echo "opened device will have index equal 0, second = 1, and so on and on.";
  echo "Superuser (root) privileges are required.";
  echo;
  echo "Usage: immudex-crypt [--list] [--create=/dev/partition] [--open=crypt_LUKS_device] [--close=index] [--help] [--version]";
  echo;
  echo "Options:";
  echo "  --list                                Prints list of opened and available crypt_LUKS devices.";
  echo "  --create=/dev/partition               Preparing device for crypt_LUKS.";
  echo "  --open=/dev/crypt_LUKS_device         Opening and mount crypt_LUKS device (create mount point, if not exist).";
  echo "  --close=index                         Unmounting and close opened crypt_LUKS devices.";
  echo "  --help                                Prints this message.";
  echo "  --version                             Print information about version, author and copyrights.";
  echo;
  echo "Examples:";
  echo "  immudex-crypt --list              List available crypt_LUKS devices in the system.";
  echo "  immudex-crypt --create=/dev/sdX   Create crypt_LUKS device from given partition.";
  echo "  immudex-crypt --open=/dev/sdX     Open given crypt_LUKS device (with mounting file system, of course).";
  echo "  immudex-crypt --close=0           Close first opened crypt_LUKS device in the system.";
  echo;
  echo "Report bugs to <xf0r3m@gmail.com>";
}

function version() {
  echo "immudex-crypt 1.0";
  echo;
  echo "Copyright (C) 2026 morketsmerke.org";
  echo "This is free software; see the source for copying conditions.  There is NO";
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
  echo;
  echo "Written by xf0r3m.";
}

function list() {

  mapperDeviceList=$(ls /dev/mapper | grep 'immudex-*' | awk '{printf $1" "}');
  
  echo "==============================================================";
  echo -e "Opened devices:";
  echo "==============================================================";
  echo -e "Device:\t\tMapper name:\t\tMount point:";

  if [ "$mapperDeviceList" ]; then
  	  for dmDevice in $mapperDeviceList; do
		    if cryptsetup status /dev/mapper/${dmDevice} > /dev/null 2>&1; then
			    mountPoint=$(df --output=source,target /dev/mapper/${dmDevice} | tail -n 1 | awk '{printf $2}');
          device=$(cryptsetup status /dev/mapper/${dmDevice} | grep "device" | awk '{printf $2}');
    		  if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
            echo -e "$device\t /dev/mapper/${dmDevice}\t$mountPoint"; 
          else
            echo -e "$device\t /dev/mapper/${dmDevice}\tNot mounted";
			    fi
		    fi
	    done 
  else
    echo -e "No opened crypt devices was found";
  fi
  echo "==============================================================";

  luksDevicesList=$(blkid | grep 'LUKS' | cut -d ":" -f 1 | awk '{printf $1" "}');

  echo "==============================================================";
  echo -e "crypt_LUKS devices:";
  echo "==============================================================";
  echo -e "Device:\t\t\tSize:";

  if [ "$luksDevicesList" ]; then
    for lDevice in $luksDevicesList; do
      lDeviceSize=$(lsblk | grep "$(basename $lDevice)" | sed -n '1p' | awk '{printf $4}');
      echo -e "$lDevice\t\t$lDeviceSize";
    done
  else
    echo "No crypt device was found";
  fi
  echo "==============================================================";
}

function open() {

  if [ $# -lt 1 ]; then help; exit 1;
  else
    index=$(ls --hide=control /dev/mapper | grep "immudex-crypt" | grep -o "[0-9]*$"| tail -1);
    if [ "$index" ]; then
      index=$((index + 1));
    else
      index=0;
    fi
    cryptsetup open $1 immudex-crypt${index};
    mkdir -p /media/${USER}/immudex-crypt${index};
    lastField=$(ls -l /dev/mapper/immudex-crypt${index} | grep -o ' ' | wc -l);
    dmDevice=$(ls -al /dev/mapper/immudex-crypt${index} | cut -d " " -f ${lastField}- | cut -d "/" -f2);
    if ! $(file -s /dev/${dmDevice} | grep -q 'ext4'); then
      echo "Could not determine filesystem of unlocked device.";
      echo -n "Format this device to ext4? (y/n): "
      read format;
      if [ "$format" = "y" ]; then
        mkfs.ext4 /dev/mapper/immudex-crypt${index};
      else
        echo "Refuse to mount.";
        cryptsetup close immudex-crypt${index};
        exit 1;
      fi
    fi
    mount /dev/mapper/immudex-crypt${index} /media/${USER}/immudex-crypt${index};
    if [ ! -e /ic${index} ]; then
      ln -s /media/${USER}/immudex-crypt${index} /ic${index};
    fi
  fi

}

function close() {

  if [ $# -lt 1 ]; then help; exit 1;
  else
    if [ $1 -ge 0 ] 2> /dev/null; then
        cryptfsName="immudex-crypt${1}";
    elif echo $1 | grep -q 'ic'; then
        cryptfsName="immudex-crypt$(echo $1 | grep -o '[0-9]')";
    else
        cryptfsName=$1;
    fi
    if cryptsetup status /dev/mapper/${cryptfsName} > /dev/null 2>&1; then
      mountPoint=$(df --output=source,target /dev/mapper/${cryptfsName} | tail -1 | awk '{printf $2}');
      if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
        umount -R $mountPoint;
        cryptsetup close ${cryptfsName};
      else
        cryptsetup close ${cryptfsName};
      fi
    else
      echo "Given devices isn't opened crypt device or it was closed before";
    fi
  fi
}

function create() {
  if [ $# -lt 1 ]; then help; exit 1;
  else
    cryptsetup -y -v luksFormat $1;
  fi
}

function set_ownership(){
  if [ $# -lt 1 ]; then help; exit 1;
  else
    mountPoint=$(list | grep "$USER" | grep "$1" | awk '{printf $3}')
    owner=$(stat -c %u $mountPoint);
    if [ $owner -eq $RUID ]; then 
      if id $USER | grep -q $RUID; then
        echo "User $USER is already owner of $mountPoint";
      fi
    else
      chown ${USER}:${USER} $mountPoint;
    fi
  fi
}

if [ "$1" ]; then

  if [ $UID -ne 0 ]; then
    echo "Permission denied!";
    help;
    exit 1;
  fi
 
  #immudex-crypt RUID is EUID of sudo, which spawning immudex-crypt
  if $(pidof -sq sudo); then
    export RUID=$(grep '^Uid:' /proc/$(pidof -s sudo)/status | awk '{printf $2}');
    export USER=$(grep "$RUID" /etc/passwd | cut -d ":" -f1);
  fi

  option=$(echo $1 | cut -d '=' -f 1);
  value=$(echo $1 | cut -d '=' -f 2-);

  case $option in
    "--list") list;;
    "--open") if [ "$value" ]; then open $value;
            else help; exit 1;
            fi;;
    "--close") if [ "$value" ]; then close $value;
            else help; exit 1;
            fi;;
    "--create") if [ "$value" ]; then 
                create $value;
                open $value;
                set_ownership $value; 
              else help; exit 1;
              fi;;
    "--help") help; exit 0;;
    "--version") version; exit 0;;
          *) help;;
  esac
else
  help; exit 1;
fi  
