#!/bin/bash

function XMLScrap() {
  echo -n $(grep -o "<${1}>.*</${1}>" $2 \
  | sed "s,<${1}>,," \
  | sed "s,</${1}>,," \
  | sed 's,&amp;,and,g');
}

function help() {
  echo "immudex-cdrip it's a bash script for collect audio tracks from Audio CD's.";
  echo "Script apart form ripping Audio CD's, reads metadata, check it on music";
  echo "databases and creates properly named directories and audio files.";
  echo;
  echo "Usage: immudex-cdrip [OPTIONS]";
  echo;
  echo "Options:";
  echo "  --rip-only        Rips audio tracks from Audio CD, without quering CDIndex (MusicBrainz) database.";
  echo "  --get-disc-info   Getting info from CDIndex (MusicBrainz) database about Audio CD without ripping.";
  echo "  --rip-n-rename    Rips audio tracks from Audio CD, create Artist/Album folders and rename tracks according to data get CDIndex (MusicBrainz) database (normal usage).";
  echo "  --help            Print this message.";
  echo "  --version         Print information about version, author and copyrights.";
  echo;
  echo "Examples:";
  echo "  immudex-cdrip                   Print this message";
  echo "  immudex-cdrip --get-disc-info   Check is in MusicBrainz DB, are there any data about puted CD in drive.";
  echo "                                  Could be useful with less popular artists.";
  echo "  immudex-cdrip --rip-n-rename    Rips Audio CD and names dirs and files with MusicBrainz data.";
  echo;
  echo "Report bugs to <xf0r3m@gmail.com>";
}

function version() {
  echo "immudex-cdrip 0.0.1";
  echo;
  echo "Copyright (C) 2027 morketsmerke.org";
  echo "This is free software; see the source for copying conditions.  There is NO";
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
  echo;
  echo "Written by xf0r3m.";
}

function multipleArtistDisc() {

  FILE="$1";
  ARTIST="VA";
  ALBUM=$(XMLScrap "Title" $FILE);
  NUMTRACKS=$(XMLScrap "NumTracks" $FILE);
  TRACKPATH="${ARTIST} - ${ALBUM}";

  mkdir -vp "${TRACKPATH}";

  i=1;
  while [ $i -le $NUMTRACKS ]; do
    artist=$(grep -o "<Artist>.*</Artist>" $FILE \
    | sed -n "${i}p" \
    | sed 's,<Artist>,,' \
    | sed 's,</Artist>,,');
 
    trackName=$(grep -o "<Name>.*</Name>" $FILE \
    | sed -n "${i}p" \
    | sed 's,<Name>,,' \
    | sed 's,</Name>,,');
  
    if [ $i -lt 10 ]; then
      trackNumber="0${i}";
    else
      trackNumber=${i};
    fi

    audioFilename="audio_${trackNumber}.wav";
    infFilename=$(echo $audioFilename | sed 's/wav/inf/');
     
    mv -v $audioFilename "${TRACKPATH}/${trackNumber}. ${artist} - ${trackName}.wav";
    rm -v ${infFilename};
    i=$(expr $i + 1);
  done

  rm -v audio.cddb;
  rm -v ${FILE};  
}

#if [ ! -x /usr/bin/cdda2wav ]; then
#  exit 1;
#fi

if [ "$1" ] && [ "$1" = "--rip-only" ]; then
  cdda2wav -vall cddb=-1 speed=4 -paranoia paraopts=no-verify -B -D /dev/sr0;
  exit 0;
fi

if [ "$1" ] && [ "$1" = "--get-disc-info" ]; then
  cdda2wav -J -D /dev/sr0;
  exit 0;
fi

if [ "$1" ] && [ "$1" = "--rip-n-rename" ]; then
  cdda2wav -vall cddb=1 speed=4 -paranoia paraopts=no-verify -B -D /dev/sr0;

  FILE="audio.cdindex";

  if $(grep -q '<MultipleArtistCD>' $FILE); then
    multipleArtistDisc $FILE;
  else  
    ARTIST=$(XMLScrap "Artist" $FILE);
    ALBUM=$(XMLScrap "Title" $FILE);
    NUMTRACKS=$(XMLScrap "NumTracks" $FILE);
    TRACKPATH="${ARTIST}/${ALBUM}";

    mkdir -vp "${TRACKPATH}";

    i=1;
    while [ $i -le $NUMTRACKS ]; do
      trackName=$(grep -o "<Name>.*</Name>" $FILE \
      | sed -n "${i}p" \
      | sed 's,<Name>,,' \
      | sed 's,</Name>,,');

      if [ $i -lt 10 ]; then
        audioFilename="audio_0${i}.wav";
        trackNumber="0${i}";
      else
        audioFilename="audio_${i}.wav";
        trackNumber="${i}";
      fi
      infFilename=$(echo "$audioFilename" | sed 's/wav/inf/');
      mv -v $audioFilename "${TRACKPATH}/${trackNumber}. ${ARTIST} - ${trackName}.wav";
      rm -v $infFilename;
      i=$(expr $i + 1);
    done
 
    rm -v audio.cddb;
    rm -v audio.cdindex;
  fi
  exit 0;
fi

if [ "$1" ] && [ "$1" = "--help" ]; then
  help;
  exit 0;
fi

if [ "$1" ] && [ "$1" = "--version" ]; then
  version;
  exit 0;
fi

help;
