#!/bin/bash

function help() {

  echo "immudex-crypt - script used for listing, open and close crypt_LUKS ppartitions";
  echo "@ 2024 morketsmerke.org";
  echo "Superuser (root) privileges are required.";
  echo "Options:";
  echo "  list - displaing list of opened and available crypt_LUKS devices";
  echo "  create - formatting device for crypt_LUKS";
  echo "  open - opening crypt_LUKS device, after this device is ready to mount";
  echo "  close - unmount and closing crypt_LUKS devices";
  echo "Using:";
  echo "# immudex-crypt list";
  echo "# immudex-crypt create <disk partition>";
  echo "# immudex-crypt open <crypt_LUKS device>";
  echo "# immudex-crypt close immudex-crypt[0-9] | ic[0-9] | [0-9]";
}

function list() {

  mapperDeviceList=$(ls /dev/mapper | grep 'immudex-*' | awk '{printf $1" "}');
  
  echo "==============================================================";
  echo -e "Opened devices:";
  echo "==============================================================";
  echo -e "Device:\t\tMapper name:\t\tMount point:";

  if [ "$mapperDeviceList" ]; then
  	  for dmDevice in $mapperDeviceList; do
		    if cryptsetup status /dev/mapper/${dmDevice} > /dev/null 2>&1; then
			    mountPoint=$(df --output=source,target /dev/mapper/${dmDevice} | tail -n 1 | awk '{printf $2}');
          device=$(sudo cryptsetup status /dev/mapper/${dmDevice} | grep "device" | awk '{printf $2}');
    		  if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
            echo -e "$device\t /dev/mapper/${dmDevice}\t$mountPoint"; 
          else
            echo -e "$device\t /dev/mapper/${dmDevice}\tNot mounted";
			    fi
		    fi
	    done 
  else
    echo -e "No opened crypt devices was found";
  fi
  echo "==============================================================";

  luksDevicesList=$(sudo blkid | grep 'LUKS' | cut -d ":" -f 1 | awk '{printf $1" "}');

  echo "==============================================================";
  echo -e "crypt_LUKS devices:";
  echo "==============================================================";
  echo -e "Device:\t\t\tSize:";

  if [ "$luksDevicesList" ]; then
    for lDevice in $luksDevicesList; do
      lDeviceSize=$(lsblk | grep "$(basename $lDevice)" | awk '{printf $4}');
      echo -e "$lDevice\t\t$lDeviceSize";
    done
  else
    echo "No crypt device was found";
  fi
  echo "==============================================================";
}

function open() {

  if [ $# -lt 1 ]; then help; exit 1;
  else
    index=$(ls --hide=control /dev/mapper | grep "immudex-crypt" | grep -o "[0-9]*$"| tail -1);
    if [ "$index" ]; then
      index=$((index + 1));
    else
      index=0;
    fi
    cryptsetup open $1 immudex-crypt${index};
    mkdir -p /media/${USER}/immudex-crypt${index};
    # Różnica w reprezentacji czasu modyfikacji miedzy Debian testing a stable i oldstable 
    #dmDevice=$(ls -l /dev/mapper/immudex-crypt${index} | awk '{printf $10}' | cut -d "/" -f 2);
    lastField=$(ls -l /dev/mapper/immudex-crypt${index} | grep -o ' ' | wc -l);
    dmDevice=$(ls -al /dev/mapper/immudex-crypt${index} | cut -d " " -f ${lastField}- | cut -d "/" -f2);
    if ! $(sudo file -s /dev/${dmDevice} | grep -q 'ext4'); then
      echo "Could not determine filesystem of unlocked device.";
      echo -n "Format this device to ext4? (y/n): "
      read format;
      if [ "$format" = "y" ]; then
        mkfs.ext4 /dev/mapper/immudex-crypt${index};
      else
        echo "Refuse to mount.";
        cryptsetup close immudex-crypt${index};
        exit 1;
      fi
    fi
    mount /dev/mapper/immudex-crypt${index} /media/${USER}/immudex-crypt${index};
    if [ ! -e /ic${index} ]; then
      ln -s /media/${USER}/immudex-crypt${index} /ic${index};
    fi
  fi

}

function close() {

  if [ $# -lt 1 ]; then help; exit 1;
  else
    if [ $1 -ge 0 ] 2> /dev/null; then
        cryptfsName="immudex-crypt${1}";
    elif echo $1 | grep -q 'ic'; then
        cryptfsName="immudex-crypt$(echo $1 | grep -o '[0-9]')";
    else
        cryptfsName=$1;
    fi
    if cryptsetup status /dev/mapper/${cryptfsName} > /dev/null 2>&1; then
      mountPoint=$(df --output=source,target /dev/mapper/${cryptfsName} | tail -1 | awk '{printf $2}');
      if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
        umount -R $mountPoint;
        cryptsetup close ${cryptfsName};
      else
        cryptsetup close ${cryptfsName};
      fi
    else
      echo "Given devices isn't opened crypt device or it was closed before";
    fi
  fi
}

function create() {
  if [ $# -lt 1 ]; then help; exit 1;
  else
    cryptsetup -y -v luksFormat $1;
  fi
}

function set_ownership(){
  if [ $# -lt 1 ]; then help; exit 1;
  else
    mountPoint=$(list | grep "$USER" | grep "$1" | awk '{printf $3}')
    owner=$(stat -c %u $mountPoint);
    if [ $owner -eq $RUID ]; then 
      if id $USER | grep -q $RUID; then
        echo "User $USER is already owner of $mountPoint";
      fi
    else
      chown ${USER}:${USER} $mountPoint;
    fi
  fi
}

if [ "$1" ]; then

  if [ $UID -ne 0 ]; then
    echo "Permission denied!";
    help;
    exit 1;
  fi
 
  #immudex-crypt RUID is EUID of sudo, which spawning immudex-crypt
  export RUID=$(grep '^Uid:' /proc/$(pidof -s sudo)/status | awk '{printf $2}');
  export USER=$(grep "$RUID" /etc/passwd | cut -d ":" -f1);

  case $1 in
    "list") list;;
    "open") if [ "$2" ]; then open $2;
            else help; exit 1;
            fi;;
    "close") if [ "$2" ]; then close $2;
            else help; exit 1;
            fi;;
    "create") if [ "$2" ]; then 
                create $2;
                open $2;
                set_ownership $2; 
              else help; exit 1;
              fi;;
          *) help;;
  esac
else
  help; exit 1;
fi  
